package com.globallogic.day5;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
//try and catch
            //try and catch both are block in java
           //there is not try block with catch block
            //catch block will receive the object of raised exception class
            //single try block and can have multiple catch



public class MyException {
	public static void main(String[] args) {

		
		//you cannot divide any number with zero
		  //divide by zero exception will be throws
		  //Arithmetic Exception
		
		
		//Exception Class : java.lang.ArithmeticException
		//Exception Message : by zero
		int a = 10;
		int b = 0;

		//int c = a / b;

		//System.out.println("c is " + c);
		
		// java.lang.NullPointerException
		//No message 
		String str=null;
		//System.out.println(str.charAt(10));
		
		int[] arr=new int[2];
		// java.lang.ArrayIndexOutOfBoundsException:
		System.out.println(arr[10]);
		
		
		//checked exception
		 //it look like error here
		//is echecked expcetion
		try
		{
	     FileInputStream ft=new FileInputStream("c:\\java.txt");
		}
		catch(FileNotFoundException e)
		{
			System.out.println("e "+e.getMessage());
		}
		catch(ArithmeticException e)
		{
			System.out.println("e "+e.getMessage());
		}
		
	}
}
